In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("dataset_v3.csv")

In [3]:
df.shape

(452, 34)

In [4]:
df.columns

Index(['PHQ_class', 'age_class', 'A2_gender', 'D1_daily_screen', 'A3_religion',
       'B1_residence', 'income_class', 'B4_family_type',
       'B5_time_with_parents_hours', 'B6_relationship_with_family',
       'weight_class', 'C3_physical_problems', 'D2_weekend_screen',
       'D3_device', 'D5_parents_screen_time', 'D6_ai_daily', 'D7_ai_impact',
       'D8_creativity_decline', 'E1_sleep_duration', 'E3_sleep_medicine',
       'E5_bedtime', 'E6_wake_time', 'F1_academic_satisfaction',
       'F4_interest_reduced', 'G1_mood_swings', 'G2_anxious_without_device',
       'G3_communication', 'G4_isolation', 'G5_negative_mental',
       'G6_panic_attack', 'H1_mobile_while_eating', 'H2_appetite_change',
       'BMI_class', 'D4_content_grouped'],
      dtype='str')

# sig or not sig

*** p<0.001, ** p<0.01, * p<0.05, ns = not significant

# with Screen Time

In [5]:
from scipy.stats import chi2_contingency

target = 'D1_daily_screen'

variables = [
    'PHQ_class', 'age_class', 'A2_gender', 'A3_religion',
    'B1_residence', 'income_class', 'B4_family_type',
    'B5_time_with_parents_hours', 'B6_relationship_with_family',
    'weight_class', 'C3_physical_problems', 'D2_weekend_screen',
    'D3_device', 'D5_parents_screen_time', 'D6_ai_daily',
    'D7_ai_impact', 'D8_creativity_decline', 'E1_sleep_duration',
    'E3_sleep_medicine', 'E5_bedtime', 'E6_wake_time',
    'F1_academic_satisfaction', 'F4_interest_reduced', 'G1_mood_swings', 'G2_anxious_without_device',
    'G3_communication', 'G4_isolation', 'G5_negative_mental',
    'G6_panic_attack', 'H1_mobile_while_eating', 'H2_appetite_change',
    'BMI_class', 'D4_content_grouped'
]

results = []
for var in variables:
    ct = pd.crosstab(df[var], df[target])
    chi2, p, dof, _ = chi2_contingency(ct)
    sig = '***' if p < 0.001 else '**' if p < 0.01 else '*' if p < 0.05 else 'ns'
    results.append({
        'Variable': var,
        'Chi2': round(chi2, 3),
        'df': dof,
        'p-value': round(p, 4),
        'Significant': sig
    })

result_df = pd.DataFrame(results)
result_df

                       Variable     Chi2  df  p-value Significant
0                     PHQ_class   27.339  12   0.0069          **
1                     age_class   91.542   6   0.0000         ***
2                     A2_gender   86.343   3   0.0000         ***
3                   A3_religion    4.007   3   0.2607          ns
4                  B1_residence   29.655   3   0.0000         ***
5                  income_class   59.413   6   0.0000         ***
6                B4_family_type    5.128   3   0.1627          ns
7    B5_time_with_parents_hours   19.550   6   0.0033          **
8   B6_relationship_with_family   10.433   6   0.1076          ns
9                  weight_class  132.978   6   0.0000         ***
10         C3_physical_problems   21.978   9   0.0089          **
11            D2_weekend_screen  270.580   3   0.0000         ***
12                    D3_device   20.553   6   0.0022          **
13       D5_parents_screen_time   45.760   3   0.0000         ***
14                  D6_ai_daily   60.341   9   0.0000         ***
15                 D7_ai_impact   22.623  12   0.0311           *
16        D8_creativity_decline   12.429   9   0.1902          ns
17            E1_sleep_duration    9.155   6   0.1650          ns
18            E3_sleep_medicine   16.740  12   0.1596          ns
19                   E5_bedtime   61.095   6   0.0000         ***
20                 E6_wake_time   28.077   6   0.0001         ***
21     F1_academic_satisfaction   35.052  12   0.0005         ***
22          F4_interest_reduced   33.810  12   0.0007         ***
23               G1_mood_swings   55.392  12   0.0000         ***
24    G2_anxious_without_device   33.404  12   0.0008         ***
25             G3_communication   12.842  12   0.3807          ns
26                 G4_isolation   26.383  12   0.0095          **
27           G5_negative_mental   13.774  12   0.3154          ns
28              G6_panic_attack   19.964  12   0.0678          ns
29       H1_mobile_while_eating   39.890  12   0.0001         ***
30           H2_appetite_change   24.213   6   0.0005         ***
31                    BMI_class   76.294   6   0.0000         ***
32           D4_content_grouped   64.432   9   0.0000         ***

In [6]:
sig_vars_st = result_df[result_df['Significant'] == '***']

In [7]:
sig_vars_st

                     Variable     Chi2  df  p-value Significant
1                   age_class   91.542   6   0.0000         ***
2                   A2_gender   86.343   3   0.0000         ***
4                B1_residence   29.655   3   0.0000         ***
5                income_class   59.413   6   0.0000         ***
9                weight_class  132.978   6   0.0000         ***
11          D2_weekend_screen  270.580   3   0.0000         ***
13     D5_parents_screen_time   45.760   3   0.0000         ***
14                D6_ai_daily   60.341   9   0.0000         ***
19                 E5_bedtime   61.095   6   0.0000         ***
20               E6_wake_time   28.077   6   0.0001         ***
21   F1_academic_satisfaction   35.052  12   0.0005         ***
22        F4_interest_reduced   33.810  12   0.0007         ***
23             G1_mood_swings   55.392  12   0.0000         ***
24  G2_anxious_without_device   33.404  12   0.0008         ***
29     H1_mobile_while_eating   39.890  12   0.0001         ***
30         H2_appetite_change   24.213   6   0.0005         ***
31                  BMI_class   76.294   6   0.0000         ***
32         D4_content_grouped   64.432   9   0.0000         ***

In [8]:
sig_vars_st_cols = sig_vars_st['Variable'].tolist()
df_sig_st = df[['D1_daily_screen'] + sig_vars_st_cols]
df_sig_st.to_csv("dataset_sig_st.csv", index=False)
df_sig_st

,D1_daily_screen,age_class,A2_gender,B1_residence,income_class,weight_class,D2_weekend_screen,D5_parents_screen_time,D6_ai_daily,E5_bedtime,E6_wake_time,F1_academic_satisfaction,F4_interest_reduced,G1_mood_swings,G2_anxious_without_device,H1_mobile_while_eating,H2_appetite_change,BMI_class,D4_content_grouped
0,3-5 hours,14-16 years,Female,Urban area,High Income (>300K),Medium (45-60 kg),3-5 and More hours,Less than 3 hours,Very rarely,Early (<9:30 PM),Late (>7:00 AM),Satisfactory,Decreased moderately,Sometimes,Sometimes,Always,Loss of appetite,Normal,Social Media & Mixed Usage
1,3-5 hours,11-13 years,Female,Urban area,Low Income (≤150K),Light (<45 kg),3-5 and More hours,Less than 3 hours,Often,Early (<9:30 PM),Late (>7:00 AM),Satisfactory,Decreased moderately,Often,Sometimes,Always,Loss of appetite,Underweight,Other
2,1-3 hours,11-13 years,Female,Urban area,Low Income (≤150K),Light (<45 kg),Less than 3 hours,Less than 3 hours,Often,Early (<9:30 PM),Normal (6:00-7:00 AM),Unsatisfactory,Not decreased at all,Occasionally,Not at all,Often,Loss of appetite,Underweight,Entertainment & Media
3,Less than 1 hour,14-16 years,Female,Urban area,High Income (>300K),Medium (45-60 kg),Less than 3 hours,Less than 3 hours,Do not use,Late (>10:30 PM),Late (>7:00 AM),Highly unsatisfactory,Not decreased at all,Always,Occasionally,Never,Overeating,Normal,Other
4,1-3 hours,14-16 years,Female,Urban area,High Income (>300K),Light (<45 kg),3-5 and More hours,3-5 hours,Do not use,Late (>10:30 PM),Normal (6:00-7:00 AM),Unsatisfactory,Not decreased at all,Always,Not at all,Often,Loss of appetite,Underweight,Other
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
447,3-5 hours,17-19 years,Male,Urban area,High Income (>300K),Medium (45-60 kg),3-5 and More hours,Less than 3 hours,Often,Early (<9:30 PM),Normal (6:00-7:00 AM),Unsatisfactory,Decreased considerably,Often,Often,Often,Overeating,Normal,Entertainment & Media
448,3-5 hours,17-19 years,Male,Urban area,High Income (>300K),Heavy (>60 kg),3-5 and More hours,3-5 hours,Almost every day,Early (<9:30 PM),Normal (6:00-7:00 AM),Highly satisfactory,Not decreased at all,Not at all,Not at all,Never,No change,Normal,Other
449,3-5 hours,17-19 years,Male,Urban area,High Income (>300K),Heavy (>60 kg),3-5 and More hours,Less than 3 hours,Almost every day,Early (<9:30 PM),Late (>7:00 AM),Moderately satisfactory,Decreased very much,Occasionally,Sometimes,Very little time,No change,Normal,Other
450,More than 5 hours,17-19 years,Male,Urban area,High Income (>300K),Heavy (>60 kg),3-5 and More hours,3-5 hours,Almost every day,Early (<9:30 PM),Late (>7:00 AM),Satisfactory,Decreased a little,Not at all,Occasionally,Never,No change,Overweight,Social Media & Mixed Usage
451,More than 5 hours,17-19 years,Male,Urban area,High Income (>300K),Heavy (>60 kg),3-5 and More hours,3-5 hours,Almost every day,Early (<9:30 PM),Late (>7:00 AM),Moderately satisfactory,Decreased moderately,Occasionally,Sometimes,Very little time,Overeating,Overweight,Other

# with PHQ9

In [9]:
from scipy.stats import chi2_contingency

target = 'PHQ_class'

variables = [
    'age_class', 'A2_gender', 'D1_daily_screen', 'A3_religion',
       'B1_residence', 'income_class', 'B4_family_type',
       'B5_time_with_parents_hours', 'B6_relationship_with_family',
       'weight_class', 'C3_physical_problems', 'D2_weekend_screen',
       'D3_device', 'D5_parents_screen_time', 'D6_ai_daily',
       'D7_ai_impact', 'D8_creativity_decline', 'E1_sleep_duration',
       'E3_sleep_medicine', 'E5_bedtime', 'E6_wake_time',
       'F1_academic_satisfaction',
       'F4_interest_reduced', 'G1_mood_swings', 'G2_anxious_without_device',
       'G3_communication', 'G4_isolation', 'G5_negative_mental',
       'G6_panic_attack', 'H1_mobile_while_eating', 'H2_appetite_change',
       'BMI_class', 'D4_content_grouped'
]

results = []
for var in variables:
    ct = pd.crosstab(df[var], df[target])
    chi2, p, dof, _ = chi2_contingency(ct)
    sig = '***' if p < 0.001 else '**' if p < 0.01 else '*' if p < 0.05 else 'ns'
    results.append({
        'Variable': var,
        'Chi2': round(chi2, 3),
        'df': dof,
        'p-value': round(p, 4),
        'Significant': sig
    })

result_df = pd.DataFrame(results)
result_df

                       Variable     Chi2  df  p-value Significant
0                     age_class   36.309   8   0.0000         ***
1                     A2_gender   15.867   4   0.0032          **
2               D1_daily_screen   27.339  12   0.0069          **
3                   A3_religion    6.830   4   0.1451          ns
4                  B1_residence    9.831   4   0.0434           *
5                  income_class   22.345   8   0.0043          **
6                B4_family_type   14.969   4   0.0048          **
7    B5_time_with_parents_hours   19.434   8   0.0127           *
8   B6_relationship_with_family   55.127   8   0.0000         ***
9                  weight_class   42.814   8   0.0000         ***
10         C3_physical_problems    6.890  12   0.8648          ns
11            D2_weekend_screen    7.815   4   0.0986          ns
12                    D3_device   26.391   8   0.0009         ***
13       D5_parents_screen_time   23.797   4   0.0001         ***
14                  D6_ai_daily   10.857  12   0.5412          ns
15                 D7_ai_impact   11.069  16   0.8052          ns
16        D8_creativity_decline   24.915  12   0.0152           *
17            E1_sleep_duration   11.808   8   0.1600          ns
18            E3_sleep_medicine   24.334  16   0.0824          ns
19                   E5_bedtime   15.934   8   0.0433           *
20                 E6_wake_time    4.069   8   0.8509          ns
21     F1_academic_satisfaction   97.822  16   0.0000         ***
22          F4_interest_reduced   34.593  16   0.0045          **
23               G1_mood_swings  140.991  16   0.0000         ***
24    G2_anxious_without_device   49.320  16   0.0000         ***
25             G3_communication   23.808  16   0.0938          ns
26                 G4_isolation   47.550  16   0.0001         ***
27           G5_negative_mental   40.302  16   0.0007         ***
28              G6_panic_attack  114.654  16   0.0000         ***
29       H1_mobile_while_eating   40.604  16   0.0006         ***
30           H2_appetite_change   25.951   8   0.0011          **
31                    BMI_class   19.800   8   0.0111           *
32           D4_content_grouped   30.100  12   0.0027          **

In [10]:
sig_vars_phq = result_df[result_df['Significant'] == '***']

In [11]:
sig_vars_phq

                       Variable     Chi2  df  p-value Significant
0                     age_class   36.309   8   0.0000         ***
8   B6_relationship_with_family   55.127   8   0.0000         ***
9                  weight_class   42.814   8   0.0000         ***
12                    D3_device   26.391   8   0.0009         ***
13       D5_parents_screen_time   23.797   4   0.0001         ***
21     F1_academic_satisfaction   97.822  16   0.0000         ***
23               G1_mood_swings  140.991  16   0.0000         ***
24    G2_anxious_without_device   49.320  16   0.0000         ***
26                 G4_isolation   47.550  16   0.0001         ***
27           G5_negative_mental   40.302  16   0.0007         ***
28              G6_panic_attack  114.654  16   0.0000         ***
29       H1_mobile_while_eating   40.604  16   0.0006         ***

In [12]:
sig_vars_phq_cols = sig_vars_phq['Variable'].tolist()
df_sig_phq = df[['PHQ_class'] + sig_vars_phq_cols]
df_sig_phq.to_csv("dataset_sig_phq9.csv", index=False)
df_sig_phq

,PHQ_class,age_class,B6_relationship_with_family,weight_class,D3_device,D5_parents_screen_time,F1_academic_satisfaction,G1_mood_swings,G2_anxious_without_device,G4_isolation,G5_negative_mental,G6_panic_attack,H1_mobile_while_eating
0,Moderate depressive,14-16 years,Good,Medium (45-60 kg),Mobile phone,Less than 3 hours,Satisfactory,Sometimes,Sometimes,Very little time,Not sure,Sometimes,Always
1,Moderate depressive,11-13 years,Good,Light (<45 kg),Mobile phone,Less than 3 hours,Satisfactory,Often,Sometimes,Very little time,Not sure,Sometimes,Always
2,Moderately Severe depressive,11-13 years,Good,Light (<45 kg),Mobile phone,Less than 3 hours,Unsatisfactory,Occasionally,Not at all,Never,Never,Very little time,Often
3,Severe depressive,14-16 years,Moderate,Medium (45-60 kg),Mobile phone,Less than 3 hours,Highly unsatisfactory,Always,Occasionally,Never,Often,Often,Never
4,Moderately Severe depressive,14-16 years,Bad,Light (<45 kg),Computer/Laptop,3-5 hours,Unsatisfactory,Always,Not at all,Never,Often,Very little time,Often
...,...,...,...,...,...,...,...,...,...,...,...,...,...
447,Mild depressive,17-19 years,Good,Medium (45-60 kg),Mobile phone,Less than 3 hours,Unsatisfactory,Often,Often,Often,Often,Often,Often
448,Minimal depressive,17-19 years,Good,Heavy (>60 kg),Mobile phone,3-5 hours,Highly satisfactory,Not at all,Not at all,Never,Always,Never,Never
449,Moderate depressive,17-19 years,Good,Heavy (>60 kg),Mobile phone,Less than 3 hours,Moderately satisfactory,Occasionally,Sometimes,Occasionally,Always,Never,Very little time
450,Minimal depressive,17-19 years,Good,Heavy (>60 kg),Tablet,3-5 hours,Satisfactory,Not at all,Occasionally,Never,Occasionally,Never,Never
451,Mild depressive,17-19 years,Good,Heavy (>60 kg),Mobile phone,3-5 hours,Moderately satisfactory,Occasionally,Sometimes,Never,Always,Never,Very little time