In [45]:
import pandas as pd

In [46]:
df = pd.read_csv("dataset_v3.csv")

In [47]:
df.shape

(452, 37)

In [48]:
df.columns

Index(['PHQ_class', 'age_class', 'A2_gender', 'D1_daily_screen', 'A3_religion',
       'B1_residence', 'income_class', 'B4_family_type',
       'B5_time_with_parents_hours', 'B6_relationship_with_family',
       'weight_class', 'C3_physical_problems', 'D2_weekend_screen',
       'D3_device', 'D4_content', 'D5_parents_screen_time', 'D6_ai_daily',
       'D7_ai_impact', 'D8_creativity_decline', 'E1_sleep_duration',
       'E3_sleep_medicine', 'E5_bedtime', 'E6_wake_time',
       'F1_academic_satisfaction', 'F2_screen_impact', 'F3_learning_interest',
       'F4_interest_reduced', 'G1_mood_swings', 'G2_anxious_without_device',
       'G3_communication', 'G4_isolation', 'G5_negative_mental',
       'G6_panic_attack', 'H1_mobile_while_eating', 'H2_appetite_change',
       'BMI_class', 'D4_content_grouped'],
      dtype='object')

# sig or not sig

*** p<0.001, ** p<0.01, * p<0.05, ns = not significant

# with Screen Time

In [49]:
from scipy.stats import chi2_contingency

target = 'D1_daily_screen'

variables = [
    'PHQ_class', 'age_class', 'A2_gender', 'A3_religion',
    'B1_residence', 'income_class', 'B4_family_type',
    'B5_time_with_parents_hours', 'B6_relationship_with_family',
    'weight_class', 'C3_physical_problems', 'D2_weekend_screen',
    'D3_device', 'D4_content', 'D5_parents_screen_time', 'D6_ai_daily',
    'D7_ai_impact', 'D8_creativity_decline', 'E1_sleep_duration',
    'E3_sleep_medicine', 'E5_bedtime', 'E6_wake_time',
    'F1_academic_satisfaction', 'F2_screen_impact', 'F3_learning_interest',
    'F4_interest_reduced', 'G1_mood_swings', 'G2_anxious_without_device',
    'G3_communication', 'G4_isolation', 'G5_negative_mental',
    'G6_panic_attack', 'H1_mobile_while_eating', 'H2_appetite_change',
    'BMI_class', 'D4_content_grouped'
]

results = []
for var in variables:
    ct = pd.crosstab(df[var], df[target])
    chi2, p, dof, _ = chi2_contingency(ct)
    sig = '***' if p < 0.001 else '**' if p < 0.01 else '*' if p < 0.05 else 'ns'
    results.append({
        'Variable': var,
        'Chi2': round(chi2, 3),
        'df': dof,
        'p-value': round(p, 4),
        'Significant': sig
    })

result_df = pd.DataFrame(results)
result_df

                       Variable     Chi2  df  p-value Significant
0                     PHQ_class   27.339  12   0.0069          **
1                     age_class   91.542   6   0.0000         ***
2                     A2_gender   86.343   3   0.0000         ***
3                   A3_religion    4.007   3   0.2607          ns
4                  B1_residence   29.655   3   0.0000         ***
5                  income_class   59.413   6   0.0000         ***
6                B4_family_type    5.128   3   0.1627          ns
7    B5_time_with_parents_hours   19.550   6   0.0033          **
8   B6_relationship_with_family   10.433   6   0.1076          ns
9                  weight_class  132.978   6   0.0000         ***
10         C3_physical_problems   21.978   9   0.0089          **
11            D2_weekend_screen  270.580   3   0.0000         ***
12                    D3_device   20.553   6   0.0022          **
13                   D4_content  131.618  30   0.0000         ***
14       D5_parents_screen_time   45.760   3   0.0000         ***
15                  D6_ai_daily   60.341   9   0.0000         ***
16                 D7_ai_impact   22.623  12   0.0311           *
17        D8_creativity_decline   12.429   9   0.1902          ns
18            E1_sleep_duration    9.155   6   0.1650          ns
19            E3_sleep_medicine   16.740  12   0.1596          ns
20                   E5_bedtime   61.095   6   0.0000         ***
21                 E6_wake_time   28.077   6   0.0001         ***
22     F1_academic_satisfaction   35.052  12   0.0005         ***
23             F2_screen_impact   18.036  12   0.1146          ns
24         F3_learning_interest   41.197   9   0.0000         ***
25          F4_interest_reduced   33.810  12   0.0007         ***
26               G1_mood_swings   55.392  12   0.0000         ***
27    G2_anxious_without_device   33.404  12   0.0008         ***
28             G3_communication   12.842  12   0.3807          ns
29                 G4_isolation   26.383  12   0.0095          **
30           G5_negative_mental   13.774  12   0.3154          ns
31              G6_panic_attack   19.964  12   0.0678          ns
32       H1_mobile_while_eating   39.890  12   0.0001         ***
33           H2_appetite_change   24.213   6   0.0005         ***
34                    BMI_class   76.294   6   0.0000         ***
35           D4_content_grouped   64.432   9   0.0000         ***

In [50]:
sig_vars_st = result_df[result_df['Significant'] == '***']

In [51]:
sig_vars_st

                     Variable     Chi2  df  p-value Significant
1                   age_class   91.542   6   0.0000         ***
2                   A2_gender   86.343   3   0.0000         ***
4                B1_residence   29.655   3   0.0000         ***
5                income_class   59.413   6   0.0000         ***
9                weight_class  132.978   6   0.0000         ***
11          D2_weekend_screen  270.580   3   0.0000         ***
13                 D4_content  131.618  30   0.0000         ***
14     D5_parents_screen_time   45.760   3   0.0000         ***
15                D6_ai_daily   60.341   9   0.0000         ***
20                 E5_bedtime   61.095   6   0.0000         ***
21               E6_wake_time   28.077   6   0.0001         ***
22   F1_academic_satisfaction   35.052  12   0.0005         ***
24       F3_learning_interest   41.197   9   0.0000         ***
25        F4_interest_reduced   33.810  12   0.0007         ***
26             G1_mood_swings   55.392  12   0.0000         ***
27  G2_anxious_without_device   33.404  12   0.0008         ***
32     H1_mobile_while_eating   39.890  12   0.0001         ***
33         H2_appetite_change   24.213   6   0.0005         ***
34                  BMI_class   76.294   6   0.0000         ***
35         D4_content_grouped   64.432   9   0.0000         ***

In [52]:
df.to_csv("sig_with_st.csv", index=False)

# with PHQ9

In [53]:
from scipy.stats import chi2_contingency

target = 'PHQ_class'

variables = [
    'age_class', 'A2_gender', 'D1_daily_screen', 'A3_religion',
       'B1_residence', 'income_class', 'B4_family_type',
       'B5_time_with_parents_hours', 'B6_relationship_with_family',
       'weight_class', 'C3_physical_problems', 'D2_weekend_screen',
       'D3_device', 'D4_content', 'D5_parents_screen_time', 'D6_ai_daily',
       'D7_ai_impact', 'D8_creativity_decline', 'E1_sleep_duration',
       'E3_sleep_medicine', 'E5_bedtime', 'E6_wake_time',
       'F1_academic_satisfaction', 'F2_screen_impact', 'F3_learning_interest',
       'F4_interest_reduced', 'G1_mood_swings', 'G2_anxious_without_device',
       'G3_communication', 'G4_isolation', 'G5_negative_mental',
       'G6_panic_attack', 'H1_mobile_while_eating', 'H2_appetite_change',
       'BMI_class', 'D4_content_grouped'
]

results = []
for var in variables:
    ct = pd.crosstab(df[var], df[target])
    chi2, p, dof, _ = chi2_contingency(ct)
    sig = '***' if p < 0.001 else '**' if p < 0.01 else '*' if p < 0.05 else 'ns'
    results.append({
        'Variable': var,
        'Chi2': round(chi2, 3),
        'df': dof,
        'p-value': round(p, 4),
        'Significant': sig
    })

result_df = pd.DataFrame(results)
result_df

                       Variable     Chi2  df  p-value Significant
0                     age_class   36.309   8   0.0000         ***
1                     A2_gender   15.867   4   0.0032          **
2               D1_daily_screen   27.339  12   0.0069          **
3                   A3_religion    6.830   4   0.1451          ns
4                  B1_residence    9.831   4   0.0434           *
5                  income_class   22.345   8   0.0043          **
6                B4_family_type   14.969   4   0.0048          **
7    B5_time_with_parents_hours   19.434   8   0.0127           *
8   B6_relationship_with_family   55.127   8   0.0000         ***
9                  weight_class   42.814   8   0.0000         ***
10         C3_physical_problems    6.890  12   0.8648          ns
11            D2_weekend_screen    7.815   4   0.0986          ns
12                    D3_device   26.391   8   0.0009         ***
13                   D4_content   74.960  40   0.0007         ***
14       D5_parents_screen_time   23.797   4   0.0001         ***
15                  D6_ai_daily   10.857  12   0.5412          ns
16                 D7_ai_impact   11.069  16   0.8052          ns
17        D8_creativity_decline   24.915  12   0.0152           *
18            E1_sleep_duration   11.808   8   0.1600          ns
19            E3_sleep_medicine   24.334  16   0.0824          ns
20                   E5_bedtime   15.934   8   0.0433           *
21                 E6_wake_time    4.069   8   0.8509          ns
22     F1_academic_satisfaction   97.822  16   0.0000         ***
23             F2_screen_impact   56.512  16   0.0000         ***
24         F3_learning_interest   14.985  12   0.2422          ns
25          F4_interest_reduced   34.593  16   0.0045          **
26               G1_mood_swings  140.991  16   0.0000         ***
27    G2_anxious_without_device   49.320  16   0.0000         ***
28             G3_communication   23.808  16   0.0938          ns
29                 G4_isolation   47.550  16   0.0001         ***
30           G5_negative_mental   40.302  16   0.0007         ***
31              G6_panic_attack  114.654  16   0.0000         ***
32       H1_mobile_while_eating   40.604  16   0.0006         ***
33           H2_appetite_change   25.951   8   0.0011          **
34                    BMI_class   19.800   8   0.0111           *
35           D4_content_grouped   30.100  12   0.0027          **

In [54]:
sig_vars_phq = result_df[result_df['Significant'] == '***']

In [55]:
sig_vars_phq

                       Variable     Chi2  df  p-value Significant
0                     age_class   36.309   8   0.0000         ***
8   B6_relationship_with_family   55.127   8   0.0000         ***
9                  weight_class   42.814   8   0.0000         ***
12                    D3_device   26.391   8   0.0009         ***
13                   D4_content   74.960  40   0.0007         ***
14       D5_parents_screen_time   23.797   4   0.0001         ***
22     F1_academic_satisfaction   97.822  16   0.0000         ***
23             F2_screen_impact   56.512  16   0.0000         ***
26               G1_mood_swings  140.991  16   0.0000         ***
27    G2_anxious_without_device   49.320  16   0.0000         ***
29                 G4_isolation   47.550  16   0.0001         ***
30           G5_negative_mental   40.302  16   0.0007         ***
31              G6_panic_attack  114.654  16   0.0000         ***
32       H1_mobile_while_eating   40.604  16   0.0006         ***

In [56]:
df.to_csv("sig_with_phq9.csv", index=False)